spring:
  application:
    name: goodsInfoService
  datasource:
    hikari:
      maximum-pool-size: 10
    url: jdbc:mysql://localhost:3306/oomall?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 112.124.5.232
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 50
        max-wait: 3000
        max-idle: 20
        min-idle: 2
    timeout: 10000
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countsql
server:
  port: 8017
eureka:
  instance:
    prefer-ip-address: true
    non-secure-port: 8017
    ip-address: 112.124.5.232
#    或者另一个我们的服务器
  client:
    serviceUrl:
      defaultZone: http://112.124.5.232:8011/eureka/
web:
  path: /picture
goods:
  redisExpireTime: 2

feign:
  hystrix:
    enabled: false
  client:
    config:
      share:
        connectTimeout: 120000
        readTimeout: 120000
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
    response:
      enabled: true