spring:
  application:
    name:Goods
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/oomall?serverTimezone=UTC
    username: root
    password: 12345678
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countsql
server:
  port: 8011
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
#    serviceUrl:
#      defaultZone:http://localhost:8080/eureka/
web:
  path:/Users/catherinewang/Desktop/picture

