spring:
  application:
    name: goodsInfoService
  datasource:
    url: jdbc:mysql://localhost:3306/oomall?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 50
        max-wait: 3000
        max-idle: 20
        min-idle: 2
    timeout: 10000
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countsql
server:
  port: 8017
eureka:
  instance:
    hostname: localhost
    metadata-map:
      instanceId: ${spring.application.name}:${spring.application.instance_id}:${random.value}
#  client:
#   serviceUrl:
#      defaultZone: http://112.124.5.232:8011/eureka/
web:
  path: /picture
goods:
  redisExpireTime: 1

